FROM python:3.10

WORKDIR /app

RUN pip install mlflow boto3

# optional: create default folders
RUN mkdir -p /app/mlruns

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "./mlruns", "--host", "0.0.0.0", "--port", "5000"]
